### ISSUE TITLE
关于获取直链的思路

### ISSUE THREAD

**Issue by etnperlong** [VergeDX/ThemeApplyTools#1]
感谢作者给我们带来这么好的一个工具，目前我在使用MIUI国际版，因此需要手动下载mtz主题进行安装
目前我在用的一个方法是[使用这个油猴脚本](https://greasyfork.org/zh-CN/scripts/374648-miui-%E4%B8%BB%E9%A2%98%E4%B8%8B%E8%BD%BD%E5%99%A8)
可以在PC先下载后复制到手机上
不知道能否将这个下载的方法更新到软件中

**Comment by VergeDX** [comment]
@etnperlong 
报歉，回复晚了
感谢您提供脚本，我会在空闲时研究一下

**Comment by VergeDX** [comment]
已初步解决，官方接口增加了一个新的字段 `?miuiUIVersion=V11`
~~等我把 AS 下回来修一下哈~~

**Comment by VergeDX** [comment]
已经修复，感谢！
@etnperlong
